trigger:
  branches:
    include:
      - 'adf'  

pr:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: destroy_initiate
    value: 'true'

stages:

  - stage: Site1_Main
    displayName: 'Site 1 - Resource Creation'
    jobs:

      # ------------------------ #
      # 1️⃣ Terraform Init
      # ------------------------ #
      - job: Site1_Init
        displayName: 'Site 1 - Terraform Init'
        steps:
          - checkout: self

          - template: site1/.pipelines/templates/terraform-init.yaml
            parameters:
              displayName: 'Terraform Init for Site 1'
              backendServiceArm: 'terraform-spn-akspipeline'
              workingDirectory: './site1'

      # ------------------------ #
      # 2️⃣ Terraform Validate
      # ------------------------ #
      - job: Site1_Validate
        displayName: 'Site 1 - Terraform Validate'
        dependsOn: Site1_Init
        condition: succeeded()
        steps:
          - checkout: self

          # Init before Validate (same as reference pipeline)
          - template: site1/.pipelines/templates/terraform-init.yaml
            parameters:
              displayName: 'Terraform Init before Validate'
              backendServiceArm: 'terraform-spn-akspipeline'
              workingDirectory: './site1'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: './site1'

      # ------------------------ #
      # 3️⃣ Terraform Plan
      # ------------------------ #
      - job: Site1_Plan
        displayName: 'Site 1 - Terraform Plan'
        dependsOn: Site1_Validate
        condition: succeeded()
        steps:
          - checkout: self

          - template: site1/.pipelines/templates/terraform-init.yaml
            parameters:
              displayName: 'Terraform Init before Plan'
              backendServiceArm: 'terraform-spn-akspipeline'
              workingDirectory: './site1'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: './site1'
              environmentServiceNameAzureRM: 'terraform-spn-akspipeline'
              args: '-out=tfplan'

      # ------------------------ #
      # 4️⃣ Terraform Apply (with output)
      # ------------------------ #
      - deployment: Site1_Apply
        displayName: 'Site 1 - Terraform Apply'
        dependsOn: Site1_Plan
        environment: 'prod'
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: site1/.pipelines/templates/terraform-init.yaml
                  parameters:
                    displayName: 'Terraform Init before Apply'
                    backendServiceArm: 'terraform-spn-akspipeline'
                    workingDirectory: './site1'
                - task: TerraformTaskV4@4
                  displayName: 'Terraform Apply'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: './site1'
                    environmentServiceNameAzureRM: 'terraform-spn-akspipeline'
                    args: '-auto-approve tfplan'

                - script: |
                    cd site1
                    echo "Extracting Terraform Outputs..."

                    gw1_ip=$(terraform output -raw gwA_public_ip)
                    echo "##vso[task.setvariable variable=gw1_public_ip;isOutput=true]$gw1_ip"

                    vpngw1_id=$(terraform output -raw vpngw_a_id)
                    echo "##vso[task.setvariable variable=vpngw_1_id;isOutput=true]$vpngw1_id"
                  displayName: 'Export Terraform Outputs'

  - stage: Site2_Main
    displayName: 'Site 2 - Resource Creation'
    jobs:

      # ------------------------ #
      # 1️⃣ Terraform Init
      # ------------------------ #
      - job: Site2_Init
        displayName: 'Site 2 - Terraform Init'
        steps:
          - checkout: self
          - template: site2/.pipelines/templates/terraform-init.yaml
            parameters:
              displayName: 'Terraform Init for Site 2'
              backendServiceArm: 'terraform-spn-site2pipeline'
              workingDirectory: './site2'

      # ------------------------ #
      # 2️⃣ Terraform Validate
      # ------------------------ #
      - job: Site2_Validate
        displayName: 'Site 2 - Terraform Validate'
        dependsOn: Site2_Init
        condition: succeeded()
        steps:
          - checkout: self

          # Init before Validate
          - template: site2/.pipelines/templates/terraform-init.yaml
            parameters:
              displayName: 'Terraform Init before Validate'
              backendServiceArm: 'terraform-spn-site2pipeline'
              workingDirectory: './site2'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: './site2'

      # ------------------------ #
      # 3️⃣ Terraform Plan
      # ------------------------ #
      - job: Site2_Plan
        displayName: 'Site 2 - Terraform Plan'
        dependsOn: Site2_Validate
        condition: succeeded()
        steps:
          - checkout: self

          - template: site2/.pipelines/templates/terraform-init.yaml
            parameters:
              displayName: 'Terraform Init before Plan'
              backendServiceArm: 'terraform-spn-site2pipeline'
              workingDirectory: './site2'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: './site2'
              environmentServiceNameAzureRM: 'terraform-spn-site2pipeline'
              args: '-out=tfplan'

      # ------------------------ #
      # 4️⃣ Terraform Apply (with output)
      # ------------------------ #
      - deployment: Site2_Apply
        displayName: 'Site 2 - Terraform Apply'
        dependsOn: Site2_Plan
        environment: 'prod'
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: site2/.pipelines/templates/terraform-init.yaml
                  parameters:
                    displayName: 'Terraform Init before Apply'
                    backendServiceArm: 'terraform-spn-site2pipeline'
                    workingDirectory: './site2'

                - task: TerraformTaskV4@4
                  displayName: 'Terraform Apply'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: './site2'
                    environmentServiceNameAzureRM: 'terraform-spn-site2pipeline'
                    args: '-auto-approve tfplan'

                - script: |
                    cd site2
                    echo "Extracting Terraform Outputs..."

                    gw2_ip=$(terraform output -raw gwB_public_ip)
                    echo "##vso[task.setvariable variable=gw2_public_ip;isOutput=true]$gw2_ip"

                    vpngw2_id=$(terraform output -raw vpngw_b_id)
                    echo "##vso[task.setvariable variable=vpngw_2_id;isOutput=true]$vpngw2_id"
                  displayName: 'Export Terraform Outputs'

# -------------------------------
# Stage 3: Site A connection.tf
# -------------------------------
- stage: SiteA_Connection
  displayName: 'Site A - Deploy Connections'
  dependsOn: SiteB_Main
  jobs:
    - job: SiteA_Connection_Init
      displayName: 'Terraform Init'
      steps:
        - checkout: self
        - task: TerraformCLI@0
          inputs:
            command: 'init'
            workingDirectory: './pipeline-site-a'
            environmentServiceNameAzureRM: 'terraform-spn-akspipeline'

    - job: SiteA_Connection_Validate
      displayName: 'Terraform Validate'
      dependsOn: SiteA_Connection_Init
      steps:
        - checkout: self
        - task: TerraformCLI@0
          inputs:
            command: 'validate'
            workingDirectory: './pipeline-site-a'

    - job: SiteA_Connection_Plan
      displayName: 'Terraform Plan'
      dependsOn: SiteA_Connection_Validate
      steps:
        - checkout: self
        - task: TerraformCLI@0
          inputs:
            command: 'plan'
            workingDirectory: './pipeline-site-a'
            environmentServiceNameAzureRM: 'terraform-spn-akspipeline'
            args: >
              -var "gwB_public_ip=$(gwB_public_ip)" 
              -var "vpngw_a_id=$(vpngw_a_id)" 
              -var "vpngw_b_id=$(vpngw_b_id)" 
              -out=tfplan

    - job: SiteA_Connection_Apply
      displayName: 'Terraform Apply'
      dependsOn: SiteA_Connection_Plan
      steps:
        - checkout: self
        - task: TerraformCLI@0
          inputs:
            command: 'apply'
            workingDirectory: './pipeline-site-a'
            environmentServiceNameAzureRM: 'terraform-spn-akspipeline'
            args: 'tfplan -auto-approve'

# -------------------------------
# Stage 4: Site B connection.tf
# -------------------------------
- stage: SiteB_Connection
  displayName: 'Site B - Deploy Connections'
  dependsOn: SiteA_Connection
  jobs:
    - job: SiteB_Connection_Init
      displayName: 'Terraform Init'
      steps:
        - checkout: self
        - task: TerraformCLI@0
          inputs:
            command: 'init'
            workingDirectory: './pipeline-site-b'
            environmentServiceNameAzureRM: 'terraform-spn-akspipeline'

    - job: SiteB_Connection_Validate
      displayName: 'Terraform Validate'
      dependsOn: SiteB_Connection_Init
      steps:
        - checkout: self
        - task: TerraformCLI@0
          inputs:
            command: 'validate'
            workingDirectory: './pipeline-site-b'

    - job: SiteB_Connection_Plan
      displayName: 'Terraform Plan'
      dependsOn: SiteB_Connection_Validate
      steps:
        - checkout: self
        - task: TerraformCLI@0
          inputs:
            command: 'plan'
            workingDirectory: './pipeline-site-b'
            environmentServiceNameAzureRM: 'terraform-spn-akspipeline'
            args: >
              -var "gwA_public_ip=$(gwA_public_ip)" 
              -var "vpngw_a_id=$(vpngw_a_id)" 
              -var "vpngw_b_id=$(vpngw_b_id)" 
              -out=tfplan

    - job: SiteB_Connection_Apply
      displayName: 'Terraform Apply'
      dependsOn: SiteB_Connection_Plan
      steps:
        - checkout: self
        - task: TerraformCLI@0
          inputs:
            command: 'apply'
            workingDirectory: './pipeline-site-b'
            environmentServiceNameAzureRM: 'terraform-spn-akspipeline'
            args: 'tfplan -auto-approve'
